#!/bin/bash
slop=$(slop -f "%x %y %w %h %g %i") || exit 1
read -r X Y W H G ID < <(echo $slop)
timestamp=$( date +%Y-%m-%d_%H-%M-%S )
ffmpeg -f x11grab -s "$W"x"$H" -i :0.0+$X,$Y -vcodec vp9 -qscale 0 -pix_fmt yuv444p -b:v 10M -r 60 ~/$timestamp.webm
