#!/bin/bash
slop=$(slop -f "%x %y %w %h %g %i") || exit 1
read -r X Y W H G ID < <(echo $slop)
timestamp=$( date +%Y-%m-%d_%H-%M-%S )
ffmpeg -f x11grab -s "$W"x"$H" -i :0.0+$X,$Y -c:v libvpx-vp9 -speed 3 -an -vf colormatrix=bt709:bt601 -b:v 0 -crf 30 -r 60 ~/$timestamp.webm
